Responsive_design
Dipeshtwis/Responsive_Design pull request #1
Opened 2020-05-26 10:15 UTC by Dipeshtwis

## the next web page clone
The project includes :

- media queries (for responsiveness)
- fluid property
- float for the navbar
- grid and flexbox

2020-05-26 23:55 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

It was hard to not approve the project because everything is great, but you did not use a mobile-first approach. 

For the project to get approved, kindly implement the changes mentioned below.

### Happy coding! :computer:

## Lucas Mazo

2020-05-26 23:55 UTC, lucasmazo32 commented on assets/css/style.css
> +@import "./reset.css";
- [ ] Hello team, this project requires you to have a Mobile-first approach. Therefore you should not have media queries for small screens. I will paste the screenshot here.

> ![image](https://user-images.githubusercontent.com/57414789/82961198-44611780-9f82-11ea-8fc7-be2522f473e0.png)

2020-05-27 13:54 UTC, Dipeshtwis commented
The project is updated which is

- based upon mobile-first approach

2020-05-27 23:53 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks:  is. Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @Dipeshtwis & @rida-elbahtouri  :+1:
- You can now merge to master. I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-05-28 07:02 UTC, merged